// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBamGUgo8VwqB8q9h-inev0WKFkQdL2V2s',
    appId: '1:687233417070:web:991730a1464376a93f4b7f',
    messagingSenderId: '687233417070',
    projectId: 'shopsmart-c9232',
    authDomain: 'shopsmart-c9232.firebaseapp.com',
    storageBucket: 'shopsmart-c9232.firebasestorage.app',
    measurementId: 'G-0WG9J2J6SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjc88w3E01RpC4TDzz15hIuzVNpkq8dBY',
    appId: '1:687233417070:android:1433245d5279fc313f4b7f',
    messagingSenderId: '687233417070',
    projectId: 'shopsmart-c9232',
    storageBucket: 'shopsmart-c9232.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA1MbVYEanNhNznBvEWqdeu4bs_lzvNNA',
    appId: '1:687233417070:ios:52a9380fdcc929123f4b7f',
    messagingSenderId: '687233417070',
    projectId: 'shopsmart-c9232',
    storageBucket: 'shopsmart-c9232.firebasestorage.app',
    iosBundleId: 'com.example.shopsmart1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA1MbVYEanNhNznBvEWqdeu4bs_lzvNNA',
    appId: '1:687233417070:ios:52a9380fdcc929123f4b7f',
    messagingSenderId: '687233417070',
    projectId: 'shopsmart-c9232',
    storageBucket: 'shopsmart-c9232.firebasestorage.app',
    iosBundleId: 'com.example.shopsmart1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBamGUgo8VwqB8q9h-inev0WKFkQdL2V2s',
    appId: '1:687233417070:web:987705f1ad5c653c3f4b7f',
    messagingSenderId: '687233417070',
    projectId: 'shopsmart-c9232',
    authDomain: 'shopsmart-c9232.firebaseapp.com',
    storageBucket: 'shopsmart-c9232.firebasestorage.app',
    measurementId: 'G-M1HSFMKG6T',
  );
}
